[project]
name = "handmark"
version = "0.1.0"
description = "Handnotes to markdown in seconds"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-inference>=1.0.0b9",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]

[project.scripts]
handmark = "main:main"
