name: Flake8 Linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  lint:
    name: Run Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E302,F541,E501,C901,W503
          # Add more comprehensive linting if needed
          flake8 src/ --count --max-complexity=10 --max-line-length=150 --statistics --ignore=E302,F541,E501
